[project]
name = "pprzpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Justin Dubois", email = "j.p.g.dubois@student.tudelft.nl" }
]
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.2",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "polars>=1.35.2",
    "pyqt6>=6.9.0",
    "scipy>=1.16.3",
]

[project.scripts]
pprzpy = "pprzpy:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
package = true
